[[protocols]]
name = "H96 IR Remote"
protocol = "nec"
variant = "necx"

[protocols.scancodes]
0x8087 = "KEY_VOLUMEUP"
0x8089 = "KEY_VOLUMEDOWN"
0x8027 = "KEY_BACK"
0x8037 = "KEY_LEFT"
0x8038 = "KEY_UP"
0x8039 = "KEY_RIGHT"
0x8040 = "KEY_DOWN"
0x8013 = "KEY_ENTER"
0x8073 = "KEY_HOME"
0x8083 = "KEY_CONTEXT_MENU"
0x8081 = "KEY_POWER"
#0x8048 = "KEY_MOUSE"

0x118 = "KEY_VOLUMEUP"
0x110 = "KEY_VOLUMEDOWN"
0x119 = "KEY_BACK"
0x151 = "KEY_LEFT"
0x116 = "KEY_UP"
0x150 = "KEY_RIGHT"
0x11a = "KEY_DOWN"
0x113 = "KEY_ENTER"
0x111 = "KEY_HOME"
0x14c = "KEY_CONTEXT_MENU"
0x140 = "KEY_POWER"
0x142 = "KEY_BACKSPACE"
0x141 = "KEY_MUTE"

0x14e = "KEY_NUMERIC_1"
0x10d = "KEY_NUMERIC_2"
0x10c = "KEY_NUMERIC_3"
0x14a = "KEY_NUMERIC_4"
0x109 = "KEY_NUMERIC_5"
0x108 = "KEY_NUMERIC_6"
0x146 = "KEY_NUMERIC_7"
0x105 = "KEY_NUMERIC_8"
0x104 = "KEY_NUMERIC_9"
0x101 = "KEY_NUMERIC_0"
0x10f = "KEY_APPSELECT"
0x14b = "KEY_REWIND"
0x14f = "KEY_FASTFORWARD"

0x1f1 = "KEY_TV_POWER"
0x1f2 = "KEY_TV_SET"
0x1f3 = "KEY_TV_N"
0x1f4 = "KEY_TV_VOLUMEUP"
0x1f5 = "KEY_TV_VOLUMEDOWN"
