[[protocols]]
name = "H96 IR Remote"
protocol = "nec"
variant = "necx"

[protocols.scancodes]
0x8087 = "KEY_VOLUMEUP"
0x8089 = "KEY_VOLUMEDOWN"
0x8027 = "KEY_BACK"
0x8037 = "KEY_LEFT"
0x8038 = "KEY_UP"
0x8039 = "KEY_RIGHT"
0x8040 = "KEY_DOWN"
0x8013 = "KEY_ENTER"
0x8073 = "KEY_HOME"
0x8083 = "KEY_CONTEXT_MENU"
0x8081 = "KEY_POWER"
#0x8048 = "KEY_MOUSE"
